#pragma once

#include <cts/commanddefs/allocate_descriptor_sets.h>
#include <cts/commanddefs/allocate_memory.h>
#include <cts/commanddefs/cmd_base.h>
#include <cts/commanddefs/cmd_begin_query.h>
#include <cts/commanddefs/cmd_begin_render_pass.h>
#include <cts/commanddefs/cmd_bind_descriptor_sets.h>
#include <cts/commanddefs/cmd_bind_index_buffer.h>
#include <cts/commanddefs/cmd_bind_pipeline.h>
#include <cts/commanddefs/cmd_bind_vertex_buffers.h>
#include <cts/commanddefs/cmd_blit_image.h>
#include <cts/commanddefs/cmd_clear_attachments.h>
#include <cts/commanddefs/cmd_clear_color_image.h>
#include <cts/commanddefs/cmd_clear_depth_stencil_image.h>
#include <cts/commanddefs/cmd_copy_buffer.h>
#include <cts/commanddefs/cmd_copy_buffer_to_image.h>
#include <cts/commanddefs/cmd_copy_image.h>
#include <cts/commanddefs/cmd_copy_image_to_buffer.h>
#include <cts/commanddefs/cmd_copy_query_pool_results.h>
#include <cts/commanddefs/cmd_dispatch.h>
#include <cts/commanddefs/cmd_dispatch_indirect.h>
#include <cts/commanddefs/cmd_draw.h>
#include <cts/commanddefs/cmd_draw_indexed.h>
#include <cts/commanddefs/cmd_draw_indexed_indirect.h>
#include <cts/commanddefs/cmd_draw_indirect.h>
#include <cts/commanddefs/cmd_end_query.h>
#include <cts/commanddefs/cmd_end_render_pass.h>
#include <cts/commanddefs/cmd_execute_commands.h>
#include <cts/commanddefs/cmd_fill_buffer.h>
#include <cts/commanddefs/cmd_next_subpass.h>
#include <cts/commanddefs/cmd_pipeline_barrier.h>
#include <cts/commanddefs/cmd_push_constants.h>
#include <cts/commanddefs/cmd_reset_event.h>
#include <cts/commanddefs/cmd_reset_query_pool.h>
#include <cts/commanddefs/cmd_resolve_image.h>
#include <cts/commanddefs/cmd_set_blend_constants.h>
#include <cts/commanddefs/cmd_set_depth_bias.h>
#include <cts/commanddefs/cmd_set_depth_bounds.h>
#include <cts/commanddefs/cmd_set_device_mask.h>
#include <cts/commanddefs/cmd_set_event.h>
#include <cts/commanddefs/cmd_set_line_width.h>
#include <cts/commanddefs/cmd_set_scissor.h>
#include <cts/commanddefs/cmd_set_stencil_compare_mask.h>
#include <cts/commanddefs/cmd_set_stencil_reference.h>
#include <cts/commanddefs/cmd_set_stencil_write_mask.h>
#include <cts/commanddefs/cmd_set_viewport.h>
#include <cts/commanddefs/cmd_update_buffer.h>
#include <cts/commanddefs/cmd_wait_events.h>
#include <cts/commanddefs/cmd_write_timestamp.h>
#include <cts/commanddefs/create_fence.h>
#include <cts/commanddefs/create_framebuffer.h>
#include <cts/commanddefs/create_graphics_pipelines.h>
#include <cts/commanddefs/create_image_view.h>
#include <cts/commanddefs/create_image.h>
#include <cts/commanddefs/create_sampler.h>
#include <cts/commanddefs/destroy_fence.h>
#include <cts/commanddefs/destroy_framebuffer.h>
#include <cts/commanddefs/destroy_image_view.h>
#include <cts/commanddefs/destroy_image.h>
#include <cts/commanddefs/destroy_pipeline.h>
#include <cts/commanddefs/destroy_sampler.h>
#include <cts/commanddefs/free_descriptor_sets.h>
#include <cts/commanddefs/free_memory.h>
#include <cts/commanddefs/get_fence_status.h>
#include <cts/commanddefs/map_memory.h>
#include <cts/commanddefs/queue_finish.h>
#include <cts/commanddefs/queue_submit.h>
#include <cts/commanddefs/reset_fences.h>
#include <cts/commanddefs/unmap_memory.h>
#include <cts/commanddefs/update_descriptor_sets.h>
#include <cts/commanddefs/wait_for_fences.h>
