#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum CtsGlDynamicStateFlagBits {
    CTS_GL_DYNAMIC_STATE_VIEWPORT_BIT = 0x00000001,
    CTS_GL_DYNAMIC_STATE_SCISSOR_BIT = 0x00000002,
    CTS_GL_DYNAMIC_STATE_LINE_WIDTH_BIT = 0x00000004,
    CTS_GL_DYNAMIC_STATE_DEPTH_BIAS_BIT = 0x00000008,
    CTS_GL_DYNAMIC_STATE_BLEND_CONSTANTS_BIT = 0x00000010,
    CTS_GL_DYNAMIC_STATE_DEPTH_BOUNDS_BIT = 0x00000020,
    CTS_GL_DYNAMIC_STATE_STENCIL_COMPARE_MASK_BIT = 0x00000040,
    CTS_GL_DYNAMIC_STATE_STENCIL_WRITE_MASK_BIT = 0x00000080,
    CTS_GL_DYNAMIC_STATE_STENCIL_REFERENCE_BIT = 0x00000100
} CtsGlDynamicStateFlagBits;

typedef enum CtsGlDescriptorType {
    CTS_GL_DESCRIPTOR_TYPE_IMAGE_INFO,
    CTS_GL_DESCRIPTOR_TYPE_BUFFER_INFO,
    CTS_GL_DESCRIPTOR_TYPE_BUFFER_VIEW,

    NUM_CTS_GL_DESCRIPTOR_TYPES
} CtsGlDescriptorType;

#ifdef __cplusplus
}
#endif