#pragma once

#include <cts/typedefs/access_flags.h>
#include <cts/typedefs/application_info.h>
#include <cts/typedefs/attachment_description.h>
#include <cts/typedefs/attachment_description_flags.h>
#include <cts/typedefs/attachment_reference.h>
#include <cts/typedefs/bool.h>
#include <cts/typedefs/buffer_copy.h>
#include <cts/typedefs/buffer_create_flags.h>
#include <cts/typedefs/buffer_image_copy.h>
#include <cts/typedefs/buffer_memory_barrier.h>
#include <cts/typedefs/buffer_usage_flags.h>
#include <cts/typedefs/buffer_view.h>
#include <cts/typedefs/buffer.h>
#include <cts/typedefs/clear_attachment.h>
#include <cts/typedefs/clear_color_value.h>
#include <cts/typedefs/clear_depth_stencil_value.h>
#include <cts/typedefs/clear_rect.h>
#include <cts/typedefs/clear_value.h>
#include <cts/typedefs/color_component_flags.h>
#include <cts/typedefs/command_buffer_begin_info.h>
#include <cts/typedefs/command_buffer_inheritance_info.h>
#include <cts/typedefs/command_buffer_reset_flags.h>
#include <cts/typedefs/command_buffer_usage_flags.h>
#include <cts/typedefs/command_buffer.h>
#include <cts/typedefs/command_pool_create_flags.h>
#include <cts/typedefs/command_pool.h>
#include <cts/typedefs/component_mapping.h>
#include <cts/typedefs/condition_variable.h>
#include <cts/typedefs/cull_mode_flags.h>
#include <cts/typedefs/dependency_flags.h>
#include <cts/typedefs/descriptor_pool_create_flags.h>
#include <cts/typedefs/descriptor_pool_size.h>
#include <cts/typedefs/descriptor_pool.h>
#include <cts/typedefs/descriptor_set_layout.h>
#include <cts/typedefs/descriptor_set.h>
#include <cts/typedefs/descriptor.h>
#include <cts/typedefs/device_memory.h>
#include <cts/typedefs/device_size.h>
#include <cts/typedefs/device.h>
#include <cts/typedefs/enums.h>
#include <cts/typedefs/event_create_flags.h>
#include <cts/typedefs/event.h>
#include <cts/typedefs/extension_properties.h>
#include <cts/typedefs/extent.h>
#include <cts/typedefs/fence_create_flags.h>
#include <cts/typedefs/fence.h>
#include <cts/typedefs/flags.h>
#include <cts/typedefs/format_feature_flags.h>
#include <cts/typedefs/format_properties.h>
#include <cts/typedefs/framebuffer_create_flags.h>
#include <cts/typedefs/framebuffer.h>
#include <cts/typedefs/graphics_pipeline.h>
#include <cts/typedefs/image_aspect_flags.h>
#include <cts/typedefs/image_blit.h>
#include <cts/typedefs/image_copy.h>
#include <cts/typedefs/image_create_flags.h>
#include <cts/typedefs/image_memory_barrier.h>
#include <cts/typedefs/image_resolve.h>
#include <cts/typedefs/image_subresource_layers.h>
#include <cts/typedefs/image_subresource_range.h>
#include <cts/typedefs/image_usage_flags.h>
#include <cts/typedefs/image_view.h>
#include <cts/typedefs/image.h>
#include <cts/typedefs/instance_create_flags.h>
#include <cts/typedefs/instance.h>
#include <cts/typedefs/mapped_memory_range.h>
#include <cts/typedefs/memory_allocate_info.h>
#include <cts/typedefs/memory_barrier.h>
#include <cts/typedefs/memory_heap_flags.h>
#include <cts/typedefs/memory_heap.h>
#include <cts/typedefs/memory_map_flags.h>
#include <cts/typedefs/memory_property_flags.h>
#include <cts/typedefs/memory_requirements.h>
#include <cts/typedefs/memory_type.h>
#include <cts/typedefs/mutex.h>
#include <cts/typedefs/offset.h>
#include <cts/typedefs/physical_device_features.h>
#include <cts/typedefs/physical_device_limits.h>
#include <cts/typedefs/physical_device_memory_properties.h>
#include <cts/typedefs/physical_device_properties.h>
#include <cts/typedefs/physical_device_sparse_properties.h>
#include <cts/typedefs/physical_device.h>
#include <cts/typedefs/pipeline_input_assembly_state_create_flags.h>
#include <cts/typedefs/pipeline_layout.h>
#include <cts/typedefs/pipeline_stage_flags.h>
#include <cts/typedefs/pipeline.h>
#include <cts/typedefs/present_info.h>
#include <cts/typedefs/push_constant_range.h>
#include <cts/typedefs/query_control_flags.h>
#include <cts/typedefs/query_pipeline_statistic_flags.h>
#include <cts/typedefs/query_pool_create_flags.h>
#include <cts/typedefs/query_pool.h>
#include <cts/typedefs/query_result_flags.h>
#include <cts/typedefs/queue_family_properties.h>
#include <cts/typedefs/queue_flags.h>
#include <cts/typedefs/queue.h>
#include <cts/typedefs/rect.h>
#include <cts/typedefs/render_pass_begin_info.h>
#include <cts/typedefs/render_pass_create_flags.h>
#include <cts/typedefs/render_pass.h>
#include <cts/typedefs/sample_count_flags.h>
#include <cts/typedefs/sampler.h>
#include <cts/typedefs/semaphore.h>
#include <cts/typedefs/shader_module.h>
#include <cts/typedefs/shader_stage_flags.h>
#include <cts/typedefs/specialization_info.h>
#include <cts/typedefs/specialization_map_entry.h>
#include <cts/typedefs/stencil_face_flags.h>
#include <cts/typedefs/stencil.h>
#include <cts/typedefs/submit_info.h>
#include <cts/typedefs/subpass_dependency.h>
#include <cts/typedefs/subpass_description_flags.h>
#include <cts/typedefs/subpass_description.h>
#include <cts/typedefs/surface_capabilities.h>
#include <cts/typedefs/surface_format.h>
#include <cts/typedefs/surface.h>
#include <cts/typedefs/swapchain.h>
#include <cts/typedefs/thread.h>
#include <cts/typedefs/vertex_input.h>
#include <cts/typedefs/viewport.h>
